### ISSUE TITLE
Silence goon executable warning

### ISSUE THREAD

**Issue by ericmj** [alco/porcelain#16]
Maybe move the executable decision to a configuration instead of always printing to stdout if a user decides to not use goon.

**Comment by ericmj** [comment]
Any updates on this?

**Comment by alco** [comment]
@ericmj sorry, I haven't worked on this. I can push an update where the warning is printed by default but can be turned off with a config option.

Could you remind me of the reason why you can't set `config :porcelain, :driver, Porcelain.Driver.Basic` instead?

**Comment by ericmj** [comment]
So setting the configuration silences in the output? In that case it is less important for me.

But I would still suggest printing with the logger, writing to stdout from a library is really bad practice. And possibly include config in the message so the user knows how to fix it.

**Comment by alco** [comment]
@ericmj thanks for your input.
