### ISSUE TITLE
** (Porcelain.UsageError) Looks like the :porcelain app is not running

### ISSUE THREAD

**Issue by sheharyarn** [alco/porcelain#30]
I'm trying to write an Elixir app (using GenServer) that spawns a Node.js server on start, and keeps it running until it's shutdown. I'm trying to use Porcelain for this, but I keep getting this error even though `:porcelain` is listed among the applications in my `mix.exs`:

```
$ mix run
== Compilation error on file lib/my_app.ex ==
** (exit) an exception was raised:
    ** (Porcelain.UsageError) Looks like the :porcelain app is not running. Make sure you've added :porcelain to the list of applications in your mix.exs.
        lib/porcelain.ex:419: Porcelain.driver/0
        lib/porcelain.ex:228: anonymous fn/3 in Porcelain.spawn/3
        lib/porcelain.ex:273: Porcelain.catch_throws/1
        lib/my_app.ex:15: MyApp.init/1
        (stdlib) gen_server.erl:328: :gen_server.init_it/6
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

Here's my GenServer:

```elixir
defmodule MyApp do
  use GenServer
  alias Porcelain.Process, as: Proc

  @node_app "#{__DIR__}/my_node_app/server.js"

  def start do
    GenServer.start_link(__MODULE__, nil)
  end

  def init(state) do
    Process.flag(:trap_exit, true)

    state = %Proc{out: stream} =
      Porcelain.spawn("node", [@node_app], [out: :stream])

    Enum.into(stream, IO.stream(:stdio, :line))

    IO.puts "Started Node Server: #{inspect(state)}"
    {:ok, state}
  end

  def terminate(reason, state) do
    IO.puts "Going Down: #{inspect(state)}"
    Proc.stop(state)
    :normal
  end
end

MyApp.start
```

If I remove the last line (`MyApp.start`), the app works (although nothing happens) but I can start it from the `iex -S mix` session. What am I doing wrong?

**Comment by sheharyarn** [comment]
Sorry about the stupid question. I did not fully understand the concept of GenServers and Supervisors fully. After carefully going through the [Mix and OTP Guide](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html) on the Elixir website, I was able to solve it myself.

**Comment by alco** [comment]
Hey, don't worry about. I'm glad you've figured it out.
